[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"

[etherscan] # Contract verification configuration
polkadot-testnet = { key = "", url = "https://blockscout-testnet.polkadot.io/api?" }
